### ISSUE TITLE
필요한 추가 API 구현

### ISSUE THREAD

**Issue by mjms0214** [MoaRoom/MoaRoom-Back#42]
## 내용

제곧내

1) step/{assignment_id}
2) /lecture/info/{assignment_id}

## 작업 내용

- [x] 과제 id로  진행 상황 [학생 이름, 학생 id, step, 점수] 반환
- [x] 과제 id로 강의 정보[강의명, 교수, 분반] 반환
- [x] 강의 정보 추가(강의 id, 교수 id)

**Comment by mjms0214** [comment]
@NayeonKeum 필요한 API 맞는지 확인해주시고 더 있으면 여기 추가해주세요~

**Comment by NayeonKeum** [comment]
귀염둥이 professorId, lectureId 추가요~
